language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - composer install --ignore-platform-reqs --no-dev

script: phpunit

cache:
  directories:
    vendor

before_cache:
  - composer update
